version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      # This should go into custom primary image, here's only for the sake of explanation
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            apt-get update && apt-get install curl -y
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin


      # This should go into custom primary image, here's only for the sake of explanation
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - setup_remote_docker


      - run:
          name: Run specs & record baselines
          command: | 
            docker login --username=dev --password=$PASS https://wallarm-dkr-dev.jfrog.io:443 
            docker pull wallarm-dkr-dev.jfrog.io:443/wallarm-fast-node:feature-FAST-1866-ll-pipelines
            docker-compose up -d dvwa fast selenium \
            &&sleep 15 \
            &&docker-compose run --service-ports test \
            &&sleep 15 \
            &&docker-compose run -e CI_MODE=testing -e BUILD_ID=$CIRCLE_WORKFLOW_ID -e TEST_RUN_URI=http://dvwa:80 fast 
